const gameGenres = {
    "iframes/subway.html": ["arcade", "action"],
    "iframes/basket.html": ["sports", "arcade", "multiplayer"],
    "iframes/retrobowl.html": ["sports", "simulation", "arcade"],
    "iframes/slope.html": ["arcade", "action"],
    "iframes/stacktris.html": ["puzzle", "arcade"],
    "iframes/run3.html": ["arcade", "platformer"],
    "iframes/brubber.html": ["racing", "action"],
    "iframes/finalearth2.html": ["strategy", "simulation"],
    "iframes/minecraft.html": ["simulation", "sandbox"],
    "iframes/eaglercraft.html": ["simulation", "sandbox"],
    "iframes/fishing.html": ["idle", "simulation"],
    "iframes/burgeria.html": ["simulation", "strategy"],
    "iframes/freezeria.html": ["simulation", "strategy"],
    "iframes/pizzeria.html": ["simulation", "strategy"],
    "iframes/hotdoggeria.html": ["simulation", "strategy"],
    "iframes/sushiria.html": ["simulation", "strategy"],
    "iframes/drivemad.html": ["racing", "puzzle"],
    "iframes/hoverracer.html": ["racing", "arcade"],
    "iframes/stickman.html": ["arcade", "action"],
    "iframes/dice.html": ["idle", "puzzle"],
    "iframes/gladihoppers.html": ["action", "arcade"],
    "iframes/flappybasketball.html": ["arcade", "sports"],
    "iframes/tunnel.html": ["arcade", "action"],
    "iframes/getaway.html": ["action", "multiplayer"],
    "iframes/gobdun.html": ["rpg", "action"],
    "iframes/minimetro.html": ["puzzle", "strategy"],
    "iframes/breaklock.html": ["puzzle"],
    "iframes/btd4.html": ["strategy", "action"],
    "iframes/btd5.html": ["strategy", "action"],
    "iframes/pokemonfr.html": ["rpg", "strategy"],
    "iframes/pokemonem.html": ["rpg", "strategy"],
    "iframes/pokemonplat.html": ["rpg", "strategy"],
    "iframes/pokemonsoulsilver.html": ["rpg", "strategy"],
    "iframes/pokemonblk.html": ["rpg", "strategy"],
    "iframes/mariokartds.html": ["racing", "arcade"],
    "iframes/gtachina.html": ["action", "fps"],
    "iframes/fred.html": ["arcade", "action"],
    "iframes/crazycattle.html": ["arcade", "action"],
    "iframes/blumgiball.html": ["sports", "arcade"],
    "iframes/jacksmith.html": ["strategy", "simulation"],
    "iframes/gswitch.html": ["arcade", "platformer", "multiplayer"],
    "iframes/pvz.html": ["strategy", "action"],
    "iframes/pvz2.html": ["strategy", "action"],
    "iframes/basketstars.html": ["sports", "arcade"],
    "iframes/totm.html": ["arcade", "action"],
    "iframes/breakout.html": ["idle", "arcade"],
    "iframes/crossyroads.html": ["arcade", "action"],
    "iframes/la2.html": ["puzzle", "simulation"],
    "iframes/buckshot.html": ["horror", "arcade"],
    "iframes/sideeffects.html": ["horror", "arcade"],
    "iframes/tag.html": ["action", "arcade", "multiplayer"],
    "iframes/shogunshowdown.html": ["strategy", "roguelike"],
    "iframes/operius.html": ["arcade", "action"],
    "https://harshulsilverspoon.github.io/cookieclickeriframe.html/": ["idle", "simulation"],
    "iframes/motox3m.html": ["racing", "arcade"],
    "iframes/portal.html": ["puzzle", "platformer"],
    "iframes/vampire.html": ["action", "roguelike"],
    "iframes/leveldevil.html": ["puzzle", "platformer"],
    "iframes/fnaf1.html": ["horror", "action"],
    "iframes/fnaf2.html": ["horror", "action"],
    "iframes/fnaf3.html": ["horror", "action"],
    "iframes/fnaf4.html": ["horror", "action"],
    "iframes/fnafsl.html": ["horror", "action"],
    "iframes/fnafps.html": ["horror", "simulation"],
    "iframes/fnafucn.html": ["horror", "action"],
    "https://harshulsilverspoon.github.io/codzombies": ["fps", "horror", "action"],
    "iframes/badguards.html": ["action", "arcade", "strategy"],
    "iframes/dire.html": ["strategy", "arcade", "action"],
    "iframes/bloxorz.html": ["puzzle"],
    "iframes/suika.html": ["puzzle", "arcade"],
    "iframes/frontwars.html": ["strategy"],
    "iframes/antimatter.html": ["idle", "simulation"],
    "iframes/snowrider.html": ["racing", "arcade"],
    "iframes/gunmayhem.html": ["action", "multiplayer"],
    "iframes/gunmayhem2.html": ["action", "multiplayer"],
    "iframes/polytrack.html": ["racing", "arcade"],
    "iframes/polytrackw+d.html": ["racing", "arcade"],
    "iframes/bitlife.html": ["simulation"],
    "iframes/ageofwar.html": ["strategy", "action"],
    "iframes/ultrakillweb.html": ["fps", "action"],
    "iframes/learntofly1.html": ["strategy", "arcade"],
    "iframes/learntofly2.html": ["strategy", "arcade"],
    "iframes/learntofly.html": ["strategy", "arcade"],
    "iframes/learntoflyidle.html": ["idle", "arcade"],
    "iframes/fireboy.html": ["puzzle", "platformer", "multiplayer"],
    "iframes/fireboy2.html": ["puzzle", "platformer", "multiplayer"],
    "iframes/fireboy3.html": ["puzzle", "platformer", "multiplayer"],
    "iframes/happywheels.html": ["action", "arcade"],
    "iframes/hollowknight.html": ["platformer", "action", "rpg"],
    "iframes/silksong.html": ["platformer", "action", "rpg"],
    "iframes/doom.html": ["fps", "action"],
    "iframes/cluster.html": ["arcade", "action"],
    "iframes/fnae.html": ["horror", "action"],
    "iframes/worldbox.html": ["simulation", "strategy"],
    "iframes/burritobison.html": ["arcade", "action"],
    "iframes/badtime.html": ["action", "arcade"],
    "iframes/deltarune.html": ["rpg"],
    "iframes/earntodie.html": ["racing", "action"],
    "iframes/rocketleague.html": ["sports", "racing"],
    "iframes/bankrobbery2.html": ["action", "fps"],
    "iframes/spacewaves.html": ["arcade", "music"],
    "iframes/soccerrandom.html": ["sports", "arcade", "multiplayer"],
    "iframes/volleyrandom.html": ["sports", "arcade", "multiplayer"],
    "iframes/boxingrandom.html": ["sports", "arcade", "multiplayer"],
    "iframes/fnf.html": ["music", "arcade"],
    "iframes/ddlc.html": ["rpg", "horror"],
    "iframes/classof09.html": ["simulation", "rpg"],
    "iframes/classof09tfs.html": ["simulation", "rpg"],
    "iframes/nubbysnumberfactory.html": ["roguelike", "arcade"],
    "iframes/isaac.html": ["action", "rpg", "horror", "roguelike"],
    "iframes/supersmashflash2.html": ["action", "arcade"],
    "iframes/papersplease.html": ["puzzle", "simulation"],
    "iframes/diceamillion.html": ["roguelike"],
    "iframes/pizzatower.html": ["platformer", "action"],
    "iframes/cloverpit.html": ["strategy", "roguelike"],
    "iframes/celeste.html": ["platformer", "action"],
    "iframes/balatro.html": ["strategy", "roguelike"],
    "iframes/dungeonsgambler.html": ["strategy", "roguelike"],
    "iframes/5b.html": ["platformer", "puzzle"],
    "iframes/osu.html": ["music", "arcade"],
    "iframes/halflife.html": ["fps", "action"],
    "iframes/shapez.html": ["puzzle", "simulation"],
    "iframes/feedthevoid.html": ["strategy"],
    "iframes/peopleplayground.html": ["simulation", "sandbox"],
    "iframes/repo.html": ["horror", "action", "roguelike"],
    "iframes/geometrydash.html": ["arcade", "music", "platformer"],
    "iframes/statetris-europe.html": ["puzzle", "arcade"],
    "iframes/fearandhunger.html": ["rpg", "horror"],
    "iframes/yomihustle.html": ["action", "strategy"],
    "iframes/ducklife1.html": ["simulation", "sports"],
    "iframes/ducklife2.html": ["simulation", "sports"],
    "iframes/ducklife3.html": ["simulation", "sports"],
    "iframes/ducklife4.html": ["simulation", "sports"],
    "iframes/sonicexe.html": ["horror", "platformer"],
    "iframes/ultrapool.html": ["sports", "arcade"],
    "iframes/baseballbros.html": ["sports"],
    "iframes/timeshooter2.html": ["fps"],
    "iframes/timeshooter3.html": ["fps"],
    "iframes/particleclicker.html": ["idle"],
    "iframes/grindcraft.html": ["idle"],
    "iframes/omori.html": ["rpg"],
    "iframes/oneshot.html": ["rpg", "puzzle"],
    "iframes/batim.html": ["rpg", "adventure", "horror", "action"],
    "iframes/adarkroom.html": ["idle"],
    "iframes/undertale.html": ["rpg"],
    "iframes/adventurecapitalist.html": ["idle"],
    "iframes/baldi.html": ["horror"],
    "iframes/undertaleyellow.html": ["rpg"],
    "iframes/ihavenomouth.html": ["horror", "rpg", "puzzle"],
    "iframes/eggycar.html": ["arcade"],
    "iframes/ragdollhit.html": ["action"],
    "iframes/ragdollarcade.html": ["arcade", "action"],
    "iframes/stardew.html": ["rpg"],
    "iframes/miside.html": ["horror", "action"],
    "iframes/helltaker.html": ["puzzle"],
    "iframes/supermario63.html": ["platformer"],
    "iframes/supermario64.html": ["platformer"],
    "iframes/basketbros.html": ["sports"],
    "iframes/inscryption.html": ["roguelike", "strategy", "horror"],
    "iframes/plagueinc.html": ["simulation", "strategy"],
    "iframes/angrybirds.html": ["arcade", "strategy"],
    "iframes/metalslug.html": ["action"],
    "iframes/granny.html": ["horror", "puzzle"],
    "iframes/notmyneighbour.html": ["horror"],
    "iframes/adgac.html": ["platformer"],
    "iframes/crueltysquad.html": ["action", "fps"],
};
