const gameNames = {
    "iframes/subway.html": "subway surfers",
    "iframes/basket.html": "basket random basketball",
    "iframes/retrobowl.html": "retro bowl football",
    "iframes/slope.html": "slope",
    "iframes/stacktris.html": "stacktris tetris",
    "iframes/run3.html": "run 3",
    "iframes/brubber.html": "burning rubber",
    "iframes/finalearth2.html": "final earth 2",
    "iframes/minecraft.html": "minecraft",
    "iframes/eaglercraft.html": "eaglercraft minecraft",
    "iframes/fishing.html": "tiny fishing",
    "iframes/burgeria.html": "papas burgeria papa's",
    "iframes/freezeria.html": "papas freezeria papa's",
    "iframes/pizzeria.html": "papas pizzeria papa's",
    "iframes/hotdoggeria.html": "papas hot doggeria papa's",
    "iframes/sushiria.html": "papas sushiria papa's",
    "iframes/drivemad.html": "drive mad",
    "iframes/hoverracer.html": "hover racer drive",
    "iframes/stickman.html": "stickman hook",
    "iframes/dice.html": "idle dice",
    "iframes/gladihoppers.html": "gladihoppers",
    "iframes/flappybasketball.html": "flappy basketball",
    "iframes/tunnel.html": "tunnel rush",
    "iframes/getaway.html": "getaway shootout",
    "iframes/gobdun.html": "gobdun",
    "iframes/minimetro.html": "mini metro",
    "iframes/breaklock.html": "break lock breaklock",
    "iframes/btd4.html": "bloons tower defense 4 btd4",
    "iframes/btd5.html": "bloons tower defense 5 btd5",
    "iframes/pokemonfr.html": "pokemon fire red",
    "iframes/pokemonem.html": "pokemon emerald",
    "iframes/pokemonplat.html": "pokemon platinum",
    "iframes/pokemonsoulsilver.html": "pokemon soulsilver soul silver",
    "iframes/pokemonblk.html": "pokemon black",
    "iframes/mariokartds.html": "mario kart ds",
    "iframes/gtachina.html": "gta chinatown wars grand theft auto",
    "iframes/fred.html": "skiing fred",
    "iframes/crazycattle.html": "crazy cattle 3d",
    "iframes/blumgiball.html": "blumgi ball",
    "iframes/jacksmith.html": "jacksmith",
    "iframes/gswitch.html": "g switch 3",
    "iframes/pvz.html": "plants vs zombies pvz",
    "iframes/pvz2.html": "plants vs zombies 2 gardenless pvz2",
    "iframes/basketstars.html": "basketball stars",
    "iframes/totm.html": "tomb of the mask",
    "iframes/breakout.html": "idle breakout",
    "iframes/crossyroads.html": "crossy road",
    "iframes/la2.html": "little alchemy 2",
    "iframes/buckshot.html": "buckshot roulette",
    "iframes/sideeffects.html": "side effects",
    "iframes/tag.html": "tag",
    "iframes/shogunshowdown.html": "shogun showdown",
    "iframes/operius.html": "operius",
    "https://harshulsilverspoon.github.io/cookieclickeriframe.html/": "cookie clicker",
    "iframes/motox3m.html": "moto x3m",
    "iframes/portal.html": "portal",
    "iframes/vampire.html": "vampire survivors",
    "iframes/leveldevil.html": "level devil",
    "iframes/fnaf1.html": "fnaf five nights at freddys 1",
    "iframes/fnaf2.html": "fnaf five nights at freddys 2",
    "iframes/fnaf3.html": "fnaf five nights at freddys 3",
    "iframes/fnaf4.html": "fnaf five nights at freddys 4",
    "iframes/fnafsl.html": "fnaf five nights at freddys 5 sister location",
    "iframes/fnafucn.html": "fnaf five nights at freddys ucn ultimate custom night",
    "iframes/fnafps.html": "fnaf five nights at freddys pizza simulator",
    "https://harshulsilverspoon.github.io/codzombies": "call of duty zombies cod nacht",
    "iframes/badguards.html": "bad guards",
    "iframes/dire.html": "dire decks",
    "iframes/bloxorz.html": "bloxorz",
    "iframes/suika.html": "suika watermelon game",
    "iframes/frontwars.html": "front wars",
    "iframes/antimatter.html": "antimatter dimensions",
    "iframes/snowrider.html": "snow rider 3d",
    "iframes/gunmayhem.html": "gun mayhem",
    "iframes/gunmayhem2.html": "gun mayhem 2",
    "iframes/polytrack.html": "polytrack",
    "iframes/polytrackw+d.html": "polytrack 0.5 winter and desert",
    "iframes/bitlife.html": "bitlife life simulator",
    "iframes/ageofwar.html": "age of war",
    "iframes/ultrakillweb.html": "ultrakill",
    "iframes/learntofly1.html": "learn to fly 1",
    "iframes/learntofly2.html": "learn to fly 2",
    "iframes/learntofly.html": "learn to fly 3",
    "iframes/learntoflyidle.html": "learn to fly idle",
    "iframes/fireboy.html": "fireboy and watergirl 1",
    "iframes/fireboy2.html": "fireboy and watergirl 2",
    "iframes/fireboy3.html": "fireboy and watergirl 3",
    "iframes/happywheels.html": "happy wheels",
    "iframes/hollowknight.html": "hollow knight",
    "iframes/silksong.html": "hollow knight silksong",
    "iframes/doom.html": "doom",
    "iframes/cluster.html": "cluster rush",
    "iframes/fnae.html": "five nights at epsteins epstein's fnae",
    "iframes/worldbox.html": "worldbox god simulator",
    "iframes/burritobison.html": "burrito bison",
    "iframes/badtime.html": "bad time simulator sans undertale",
    "iframes/deltarune.html": "deltarune undertale",
    "iframes/earntodie.html": "earn to die",
    "iframes/rocketleague.html": "rocket league",
    "iframes/bankrobbery2.html": "bank robbery 2",
    "iframes/spacewaves.html": "space waves geometry dash",
    "iframes/soccerrandom.html": "soccer random",
    "iframes/volleyrandom.html": "volley random volleyball",
    "iframes/boxingrandom.html": "boxing random",
    "iframes/fnf.html": "friday night funkin fnf",
    "iframes/ddlc.html": "ddlc doki doki literature club",
    "iframes/classof09.html": "class of 09 '09",
    "iframes/classof09tfs.html": "class of 09 '09 the flip side tfs",
    "iframes/nubbysnumberfactory.html": "nubbys number factory nubby's",
    "iframes/isaac.html": "the binding of isaac wrath of the lamb",
    "iframes/supersmashflash2.html": "super smash flash 2 super smash bros ssf2",
    "iframes/papersplease.html": "papers please",
    "iframes/diceamillion.html": "dice a million",
    "iframes/pizzatower.html": "pizza tower",
    "iframes/cloverpit.html": "cloverpit clover pit",
    "iframes/celeste.html": "celeste",
    "iframes/balatro.html": "balatro",
    "iframes/dungeonsgambler.html": "dungeons and degenerate gamblers",
    "iframes/5b.html": "battle for dream island again 5b bfdia 5b",
    "iframes/osu.html": "osu!",
    "iframes/halflife.html": "half life halflife",
    "iframes/shapez.html": "shapez.io",
    "iframes/feedthevoid.html": "feed the void",
    "iframes/peopleplayground.html": "people playground",
    "iframes/geometrydash.html": "geometry dash",
    "iframes/repo.html": "repo r.e.p.o",
    "iframes/statetris-europe.html": "statetris europe tetris",
    "iframes/fearandhunger.html": "fear and hunger",
    "iframes/yomihustle.html": "your only move is hustle yomi hustle",
    "iframes/ducklife1.html": "ducklife 1 duck life",
    "iframes/ducklife2.html": "ducklife 2 duck life",
    "iframes/ducklife3.html": "ducklife 3 duck life",
    "iframes/ducklife4.html": "ducklife 4 duck life",
    "iframes/sonicexe.html": "sonic exe sonic.exe",
    "iframes/ultrapool.html": "ultrapool ultra pool",
    "iframes/baseballbros.html": "baseball bros!",
    "iframes/timeshooter2.html": "time shooter 2",
    "iframes/timeshooter3.html": "time shooter 3 swat",
    "iframes/particleclicker.html": "particle clicker",
    "iframes/grindcraft.html": "grindcraft minecraft",
    "iframes/omori.html": "omori",
    "iframes/oneshot.html": "oneshot",
    "iframes/batim.html": "bendy and the ink machine batim",
    "iframes/adarkroom.html": "a dark room adr",
    "iframes/undertale.html": "undertale",
    "iframes/adventurecapitalist.html": "adventure capitalist",
    "iframes/baldi.html": "baldi's basics plus baldis basic plus",
    "iframes/undertaleyellow.html": "undertale yellow",
    "iframes/ihavenomouth.html": "i have no mouth and i must scream ihnmaims",
    "iframes/eggycar.html": "eggy car",
    "iframes/ragdollhit.html": "ragdoll hit",
    "iframes/ragdollarcher.html": "ragdoll archer",
    "iframes/stardew.html": "stardew valley",
    "iframes/helltaker.html": "helltaker",
    "iframes/miside.html": "miside",
    "iframes/supermario63.html": "super mario 63",
    "iframes/supermario64.html": "super mario 64",
    "iframes/basketbros.html": "basketball basket bros",
    "iframes/inscryption.html": "inscryption",
    "iframes/plagueinc.html": "plague inc",
    "iframes/angrybirds.html": "angry birds",
    "iframes/metalslug.html": "metal slug 3",
    "iframes/granny.html": "granny",
    "iframes/notmyneighbour.html": "that's thats not my neighbour",
    "iframes/crueltysquad.html": "cruelty squad",
    "iframes/adgac.html": "a difficult game about climbing",
};
